name: Compilar IPA iPhone

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4

      - name: Mostrar Xcode
        run: xcodebuild -version

      - name: Compilar sin firma
        run: |
          xcodebuild \
            -project SoffastPagoSonoro.xcodeproj \
            -scheme SoffastPagoSonoro \
            -sdk iphoneos \
            -configuration Release \
            -derivedDataPath build \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            clean build

      - name: Crear IPA
        run: |
          mkdir -p Payload
          cp -R build/Build/Products/Release-iphoneos/SoffastPagoSonoro.app Payload/
          zip -qry Soffast_Pago_Sonoro_iPhone_Gratis_V1.ipa Payload

      - name: Publicar IPA
        uses: actions/upload-artifact@v4
        with:
          name: Soffast-Pago-Sonoro-iPhone-IPA
          path: Soffast_Pago_Sonoro_iPhone_Gratis_V1.ipa
          retention-days: 7
